### ISSUE TITLE
Reown latest Flutter SDK Issue (1.4.2 + 1)

### ISSUE THREAD

**Issue by Shyam-Kumar-GBXBP** [reown-com/reown_flutter#150]
**SDK Affected**

AppKit 

**Describe the bug**

In Sdk version(1.4.2 + 1) facing late initialization error once we go back and come to the  reown screen. This initialization works fine on sdk version 1.3.0. There is an issue while initiating the smart contract, its not behaving properly mainly for Coinbase wallet. Checked with the FL Appkit (example project its working fine) but when tried to implement the same logic still the issue persists. It would be great if the team can help us. Thank you.  @quetool 

**To Reproduce**

1st issue:
• In sdk version (1.4.2 + 1) once initialized in a screen going back and coming again its causing late initialization error (@walletdata already initialized) this dosent happen on 1.3.0
2nd issue:
• While initiating the smart contract, its not behaving properly mainly for Coinbase wallet because the topic value is not available and while initiating requestWriteContract it throws an null error.
• In Sdk version 1.3.0 used request method instead able to deeplink to coinbase but the transaction pop up to times and coinabase throws an error. 

**Smartphone (please complete the following information):**

 - Device: iPhone and android

**Comment by quetool** [comment]
Thanks @Shyam-Kumar-GBXBP! I'm going to take a look!

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, can you write up a little example code to reproduce first issue?

**Comment by Shyam-Kumar-GBXBP** [comment]
Hi @quetool Any update on the issues ??

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP , I'm looking into it.

**Comment by Shyam-Kumar-GBXBP** [comment]
Thank you @quetool

**Comment by Shyam-Kumar-GBXBP** [comment]
Awesome @quetool Sure.

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, can you try `reown_appkit: ^1.4.2+2`?

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, I will look at those issue on a separated branch (new version) as it requires a bit more of investigation.

**Comment by Shyam-Kumar-GBXBP** [comment]
Hi @quetool As I tested now the late init issue is Fixed and its working fine the wallet state is maintained. Thanks for the update. We are blocked on the other two mentioned issues its a road blocker for our launch.

**Comment by quetool** [comment]
I'll take a look at it today!

**Comment by quetool** [comment]
Hello @Shyam-Kumar-GBXBP, can you install this temporary dependency and let me know if Coinbase Wallet gets opened?

```
reown_appkit:
    git:
      url: https://github.com/reown-com/reown_flutter.git
      path: packages/reown_appkit
      ref: 7d7a8ef65e2ed47d6e959f8ac8921c084b02123b
```

**Comment by Shyam-Kumar-GBXBP** [comment]
@quetool When using this dependency the connect wallet button is greyed out and not able to select. Kindly check this one.

**Comment by quetool** [comment]
Thanks! It's fixed! Please try this one:

```
reown_appkit:
    git:
      url: https://github.com/reown-com/reown_flutter.git
      path: packages/reown_appkit
      ref: 19e246a134a928c69bf1643ddccd9289f7e08504
```

**Comment by Shyam-Kumar-GBXBP** [comment]
@quetool Thanks for the update, when using this dependency the imports are not working as i checked the reown appkit code is missing. Kindly check this one.

**Comment by quetool** [comment]
This version is exactly the same as the previous one, I just fixed a couple of issues

**Comment by quetool** [comment]
> Hi @quetool Thank you. My bad, there was an issue in my pubspec.yaml sorted it now it's working fine. Tested connecting to the coinbase wallet still the topic is null.

The topic is null with Coinbase because Coinbase doesn't use WalletConnect protocol so the request goes through their own linking method. Same with Phantom Wallet. This shouldn't be an issue for you anyway.

**Comment by Shyam-Kumar-GBXBP** [comment]
Thanks For the update @quetool , In that case i am using this piece of code for initiating a USDC smart contract. This works fine for metamask since it has topic. Since topic will be null for coinbase wallet how to initiate a smart contract to send USDC and USDT. Kindly help with this. It would be great if you can share a sample code for initiating a smart contract for coinbase wallet.
 final result = await widget.service.requestWriteContract(
          topic: widget.service.session!.topic,
          chainId: 'eip155:$chainId',
          deployedContract: widget.contract,
          functionName: 'transfer',
          parameters: [recipient, amount], transaction: transaction,
        );

**Comment by quetool** [comment]
You are doing it properly, here it is an example on our sample dapp: https://github.com/reown-com/reown_flutter/blob/ebc389d18bba40c363e0d2cf06696d7ff29d76a3/packages/reown_appkit/example/modal/lib/services/methods_service.dart#L327

**Comment by Shyam-Kumar-GBXBP** [comment]
Hi @quetool, Thanks for the code. I tried with it but still facing the issue. I used the same code to initiate a smart contract. Tried both request and readWriteRequest methods, as soon as i go to coinbase wallet the popup comes twice and coinbase declines it. Kindly have a look on the video and sharing my transfer code. 
https://drive.google.com/file/d/1h1Cj9iUs4jYXbk4B9N_T7OdhorbeTGLy/view?usp=sharing


Future<void> _transferToken(
    String toAddress, Function(bool success) completion) async {
  if (widget._walletAddress.isNotEmpty &&
      baseAmountController.text.isNotEmpty) {
    final walletAddress = widget._walletAddress;
    //Utility.showGlobalSpinner(context);

    final session = widget.appkitModal.session;
    if (session == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content:
              Text('Session not initialized. Please reconnect your wallet.'),
        ),
      );
      Utility.hideGlobalSpinner(context);
      return;
    }

    try {
      final sender = EthereumAddress.fromHex(walletAddress);
      final recipient = EthereumAddress.fromHex(toAddress) ;
   

      final amount = BigInt.from(double.parse(baseAmountController.text) 
          1e6); // USDC on Polygon = 6 decimals
      final transferFunction = widget.contract.function('transfer');
      final data = transferFunction.encodeCall([recipient, amount]);
      final chainId = widget.selectedChain;

      final transaction = Transaction(
        from: sender,
        to: recipient,
        data: data,
        // REMOVE this line: gasPrice: EtherAmount.inWei(BigInt.from(0)),
        maxGas: 200000, // USDC transfers usually need ~100K–150K gas
      );
      // Future.delayed(Duration(seconds: 2)).then((value) {
      //   widget.appkitModal.launchConnectedWallet();
      // });

      final trx = Transaction.callContract(
        contract: widget.contract,
        function: widget.contract.function('transfer'),
        from: transaction.from!,
        value: transaction.value,
        maxGas: transaction.maxGas,
        gasPrice: transaction.gasPrice,
        nonce: transaction.nonce,
        maxFeePerGas: transaction.maxFeePerGas,
        maxPriorityFeePerGas: transaction.maxPriorityFeePerGas,
        parameters: [
          recipient,
            amount,
           ],
      );

      var result =  await widget.appkitModal.request(
        topic: widget.appkitModal.session!.topic,
        chainId: 'eip155:$chainId',
        request: SessionRequestParams(
          method: MethodsConstants.ethSendTransaction,
          params: [trx.toJson()],
        ),
      );
      // await widget.appkitModal.requestWriteContract(
      //   topic: widget.appkitModal.session!.topic,
      //   chainId: 'eip155:$chainId',
      //   deployedContract: widget.contract,
      //   functionName: 'transfer',
      //   parameters: [recipient, amount],
      //   transaction: transaction,
      // );
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Transfer successful! Transaction ID: ${result.toString()}',
          ),
        ),
      );
      await _fetchTokenBalance();
      if (result.toString().isNotEmpty) {
        completion((result.toString().isNotEmpty) ? true : false);
      }
      //completion((result.toString().isNotEmpty) ? true : false);
    } catch (e) {
      print("transfer error");
      Utility.hideGlobalSpinner(
          context); // move this outside the catch to ensure it's hidden
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Transfer error: $e'),
        ),
      );
    }
  } else {
    Utility.hideGlobalSpinner(context);
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text(
            'Enter Recipient Address and Amount to initiate the transfer'),
      ),
    );
  }
}

**Comment by quetool** [comment]
Hello, what you see in the video is most probably an issue on Coinbase side. I already reached out to them to provide a solution. The proof is that works with any other wallet.

**Comment by Shyam-Kumar-GBXBP** [comment]
Got it, thank you @quetool . Please update us once coinbase base team fixes the issue, because we are keeping the coinbase wallet as priority wallet for us and we are planning to launch in 20days.

**Comment by quetool** [comment]
Any particular reason why you configure Coinbase as priority wallet? Just trying to understand if we can do something more from product side considering that Coinbase doesn't support WalletConnect secure protocol.

**Comment by quetool** [comment]
Hello, I haven't heard back from Coinbase team, I'll reach out again today

**Comment by Shyam-Kumar-GBXBP** [comment]
Hi @quetool did they get back regarding the smart contract ??
